version: '3.8'

services:
  media_clip:
    container_name: media_clip_api
    image: media-clip:v0.1
    volumes:
      - /data:/data
      - ./.cache:/root/.cache
    ports:
      - "3336:3336"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    restart: always
    # command: tail -f /dev/null